### ISSUE TITLE
Using docker when capturing packets?

### ISSUE THREAD

**Issue by MilesCranmer** [ledatelescope/bifrost#65]
I have a question about using Docker for Bifrost on ADP.

As @benbarsdell said today at the telecon, many companies are starting to use docker for production. I  suppose the big advantage is that you don't need to build/test a software on each system. You build the software one time and run it everywhere with native performance

Since we would like to have Bifrost running for many different data capture use cases, it would be interesting to capture packets from inside a Docker container and demonstrate no loss of speed. Then we would have stronger evidence for how easy it is to set up a real-time data capture backend with Bifrost.

Thoughts?

**Comment by benbarsdell** [comment]
This would be a great demo.

One clarification regarding performance: "native" as you mean it will still
require compiling specifically for the target CPU architecture. This is
independent of Docker though. Containers take care of all your dependencies
and run natively on the hardware, but the binaries still need to be
specific to that hardware to get peak performance.

On 20 Jan 2017 7:41 pm, "Miles Cranmer" <notifications@github.com> wrote:

I have a question about using Docker for Bifrost on ADP.

As @benbarsdell <https://github.com/benbarsdell> said today at the telecon,
many companies are starting to use docker for production. I suppose the big
advantage is that you don't need to build/test a software on each system.
You build the software one time and run it everywhere with native
performance

Since we would like to have Bifrost running for many different data capture
use cases, it would be interesting to capture packets from inside a Docker
container and demonstrate no loss of speed. Then we would have stronger
evidence for how easy it is to set up a real-time data capture backend with
Bifrost.

Thoughts?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ledatelescope/bifrost/issues/65>, or mute the thread

**Comment by MilesCranmer** [comment]
Interesting. So is it that `docker build` (building a docker image from source on the machine) achieves native performance, but if I do a `docker pull` for an image from some repository, I might not?

**Comment by jaycedowell** [comment]
After talking with @MilesCranmer my current thinking is that the most users wanting to do packet capture also want to be as close to the hardware as possible and will not be using Docker.  Docker might still have a place for tutorials and offline portable pipelines.  I'm closing this for now but if anyone is interested in trying it, feel free to reopen this issue.
